using System;
using System.Collections.Generic;

namespace VAICOM.Extensions.WSO
{
    public static class WSOLabels
    {
        // Labels for WSO commands
        public static readonly Dictionary<string, string> aicommands = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // Labels for WSO commands
            { "wMsgWSO_ReportSpeed", "WSO: Report Speed" },
            { "wMsgWSO_ToggleRadar", "WSO: Toggle Radar" },
            { "wMsgWSO_SetChaffMode", "WSO: Set Chaff Mode" },
            { "wMsgWSO_LantirnDesignate", "WSO: LANTIRN Designate" },
            { "wMsgWSO_LantirnUndesignate", "WSO: LANTIRN Undesignate" },
            { "wMsgWSO_RadarGoSilent", "WSO: Radar Go Silent" },
            { "wMsgWSO_RadarGoActive", "WSO: Radar Go Active" },
            { "wMsgWSO_SetManualFrequency", "WSO: Set Manual Frequency" },
            { "wMsgWSO_SelectCommChannel", "WSO: Select Comm Channel" },
            { "wMsgWSO_SelectAuxChannel", "WSO: Select Aux Channel" },
            { "wMsgWSO_TuneATC", "WSO: Tune ATC" },
            { "wMsgWSO_TuneAssets", "WSO: Tune Assets" },
            { "wMsgWSO_SelectMode", "WSO: Select Mode" },
            { "wMsgWSO_RadarOperationActive", "WSO: Radar Operation Active" },
            { "wMsgWSO_RadarOperationStandby", "WSO: Radar Operation Standby" },
            { "wMsgWSO_RadarAutoFocusOn", "WSO: Radar Auto Focus On" },
            { "wMsgWSO_RadarAutoFocusOff", "WSO: Radar Auto Focus Off" },
            { "wMsgWSO_RadarIFFBoth", "WSO: Radar IFF Both" },
            { "wMsgWSO_RadarIFFAPX76", "WSO: Radar IFF APX-76" },
            { "wMsgWSO_RadarEnterBoresight", "WSO: Radar Enter Boresight" },
            { "wMsgWSO_RadarBoresightWide", "WSO: Radar Boresight Wide" },
            { "wMsgWSO_RadarBoresightNose", "WSO: Radar Boresight Nose" },
            { "wMsgWSO_RadarBoresightForward", "WSO: Radar Boresight Forward" },
            { "wMsgWSO_RadarBoresightAft", "WSO: Radar Boresight Aft" },
            { "wMsgWSO_RadarBoresightTail", "WSO: Radar Boresight Tail" },
            { "wMsgWSO_RadarScanElevationCenter", "WSO: Radar Scan Elevation Center" },
            { "wMsgWSO_RadarScanElevationLow", "WSO: Radar Scan Elevation Low" },
            { "wMsgWSO_RadarScanElevationMidLow", "WSO: Radar Scan Elevation Mid Low" },
            { "wMsgWSO_RadarScanElevationFarLow", "WSO: Radar Scan Elevation Far Low" },
            { "wMsgWSO_RadarScanElevationCloseHigh", "WSO: Radar Scan Elevation Close High" },
            { "wMsgWSO_RadarScanElevationMidHigh", "WSO: Radar Scan Elevation Mid High" },
            { "wMsgWSO_RadarScanElevationFarHigh", "WSO: Radar Scan Elevation Far High" },
            { "wMsgWSO_RadarScanType25Wide", "WSO: Radar Scan Type 25 Wide" },
            { "wMsgWSO_RadarScanType25Narrow", "WSO: Radar Scan Type 25 Narrow" },
            { "wMsgWSO_RadarScanType50Wide", "WSO: Radar Scan Type 50 Wide" },
            { "wMsgWSO_RadarScanType50Narrow", "WSO: Radar Scan Type 50 Narrow" },
            { "wMsgWSO_RadarFocusTarget", "WSO: Radar Focus Target" },
            { "wMsgWSO_RadarLockTarget", "WSO: Radar Lock Target" },
            { "wMsgWSO_A2GTVWeapons", "WSO: A2G TV Weapons" },
            { "wMsgWSO_A2GTVPaveSpike", "WSO: A2G TV Pave Spike" },
            { "wMsgWSO_NavigationGoToResume", "WSO: Navigation Go To Resume" },
            { "wMsgWSO_NavigationHoldingCurrentTurnPoint", "WSO: Navigation Holding Current Turn Point" },
            { "wMsgWSO_NavigationDivertLatLong", "WSO: Navigation Divert Lat Long" },
            { "wMsgWSO_NavigationTACANSelectModeOff", "WSO: Navigation TACAN Select Mode Off" },
            { "wMsgWSO_NavigationTACANSelectModeR", "WSO: Navigation TACAN Select Mode R" },
            { "wMsgWSO_NavigationTACANSelectModeTR", "WSO: Navigation TACAN Select Mode TR" },
            { "wMsgWSO_NavigationTACANSelectModeAAR", "WSO: Navigation TACAN Select Mode AAR" },
            { "wMsgWSO_NavigationTACANSelectModeAATR", "WSO: Navigation TACAN Select Mode AATR" },
            { "wMsgWSO_SystemsChaffModeOff", "WSO: Systems Chaff Mode Off" },
            { "wMsgWSO_SystemsChaffModeSingle", "WSO: Systems Chaff Mode Single" },
            { "wMsgWSO_SystemsChaffModeMultiple", "WSO: Systems Chaff Mode Multiple" },
            { "wMsgWSO_SystemsChaffModeProgram", "WSO: Systems Chaff Mode Program" },
            { "wMsgWSO_SystemsFlareModeOff", "WSO: Systems Flare Mode Off" },
            { "wMsgWSO_SystemsFlareModeSingle", "WSO: Systems Flare Mode Single" },
            { "wMsgWSO_SystemsFlareModeProgram", "WSO: Systems Flare Mode Program" },
            { "wMsgWSO_SystemsJammerStandby", "WSO: Systems Jammer Standby" },
            { "wMsgWSO_SystemsJammerTransmit", "WSO: Systems Jammer Transmit" },
            { "wMsgWSO_SystemsAVTRRecord", "WSO: Systems AVTR Record" },
            { "wMsgWSO_SystemsAVTRStandby", "WSO: Systems AVTR Standby" },
            { "wMsgWSO_SystemsAVTROff", "WSO: Systems AVTR Off" },
            { "wMsgWSO_CrewPresenceAuto", "WSO: Crew Presence Auto" },
            { "wMsgWSO_CrewPresenceForce", "WSO: Crew Presence Force" },
            { "wMsgWSO_CrewPresenceDisable", "WSO: Crew Presence Disable" },
            { "wMsgWSO_CrewTalkingTalk", "WSO: Crew Talking Talk" },
            { "wMsgWSO_CrewTalkingSilence", "WSO: Crew Talking Silence" },
            { "wMsgWSO_CrewEjectionWSO", "WSO: Crew Ejection WSO" },
            { "wMsgWSO_CrewEjectionBoth", "WSO: Crew Ejection Both" },
            { "wMsgWSO_CrewCountermeasuresManual", "WSO: Crew Countermeasures Manual" },
            { "wMsgWSO_CrewCountermeasuresJester", "WSO: Crew Countermeasures Jester" },
        };
    }
}