using System.Collections.Generic;

namespace VAICOM.WSO
{
    public static class WSOCommandMappings
    {
        public static readonly Dictionary<string, (string category, string action, string value)> CommandMap = new Dictionary<string, (string, string, string)>
        {
            // Existing commands
            { "Jester.ReportSpeed", ("jester", "report_speed", "") },
            { "Jester.ToggleRadar", ("jester", "toggle_radar", "") },
            { "Jester.SetChaffMode", ("jester", "set_chaff_mode", "MULT") },
            { "Jester.Lantirn.Designate", ("jester", "lantirn_designate", "") },
            { "Jester.Lantirn.Undesignate", ("jester", "lantirn_undesignate", "") },
            { "Jester.Radar.GoSilent", ("jester", "radar_go_silent", "") },
            { "Jester.Radar.GoActive", ("jester", "radar_go_active", "") },

            // Extracted commands from interface.js
            { "Jester.Radio.SetManualFrequency", ("radio", "radio_manual_freq_text", "") },
            { "Jester.Radio.SelectCommChannel", ("radio", "radio_comm_chan", "") },
            { "Jester.Radio.SelectAuxChannel", ("radio", "radio_aux_chan", "") },
            { "Jester.Radio.TuneATC", ("radio", "radio_tune_atc_thinking", "") },
            { "Jester.Radio.TuneAssets", ("radio", "radio_tune_asset_thinking", "") },
            { "Jester.Radio.SelectMode", ("radio", "radio_mode", "") },
            { "Jester.Radar.Operation.Active", ("radar", "radar_op", "active") },
            { "Jester.Radar.Operation.Standby", ("radar", "radar_op", "standby") },
            { "Jester.Radar.AutoFocus.On", ("radar", "radar_auto_focus", "on") },
            { "Jester.Radar.AutoFocus.Off", ("radar", "radar_auto_focus", "off") },
            { "Jester.Radar.IFF.Both", ("radar", "radar_iff", "both") },
            { "Jester.Radar.IFF.APX76", ("radar", "radar_iff", "apx_76") },
            { "Jester.Radar.Boresight.EnterBST", ("radar", "radar_enter_bst", "") },
            { "Jester.Radar.Boresight.Wide", ("radar", "radar_bst_aspect", "wide") },
            { "Jester.Radar.Boresight.Nose", ("radar", "radar_bst_aspect", "nose") },
            { "Jester.Radar.Boresight.Forward", ("radar", "radar_bst_aspect", "fwd") },
            { "Jester.Radar.Boresight.Aft", ("radar", "radar_bst_aspect", "aft") },
            { "Jester.Radar.Boresight.Tail", ("radar", "radar_bst_aspect", "tail") },
            { "Jester.Radar.ScanElevation.Center", ("radar", "radar_scan_zone", "30;0;relative") },
            { "Jester.Radar.ScanElevation.Low", ("radar", "radar_scan_zone", "30;-3.5;relative") },
            { "Jester.Radar.ScanElevation.MidLow", ("radar", "radar_scan_zone", "30;-5;relative") },
            { "Jester.Radar.ScanElevation.FarLow", ("radar", "radar_scan_zone", "30;-7.5;relative") },
            { "Jester.Radar.ScanElevation.CloseHigh", ("radar", "radar_scan_zone", "30;3.5;relative") },
            { "Jester.Radar.ScanElevation.MidHigh", ("radar", "radar_scan_zone", "30;5;relative") },
            { "Jester.Radar.ScanElevation.FarHigh", ("radar", "radar_scan_zone", "30;7.5;relative") },
            { "Jester.Radar.ScanType.25Wide", ("radar", "radar_display_range", "nm_25;wide") },
            { "Jester.Radar.ScanType.25Narrow", ("radar", "radar_display_range", "nm_25;narrow") },
            { "Jester.Radar.ScanType.50Wide", ("radar", "radar_display_range", "nm_50;wide") },
            { "Jester.Radar.ScanType.50Narrow", ("radar", "radar_display_range", "nm_50;narrow") },
            { "Jester.Radar.FocusTarget", ("radar", "radar_focus_targets_thinking", "") },
            { "Jester.Radar.LockTarget", ("radar", "radar_lock_targets_thinking", "") },
            { "Jester.A2G.TVWeapons", ("a2g", "a2g_tv_feed", "weapons") },
            { "Jester.A2G.TVPaveSpike", ("a2g", "a2g_tv_feed", "pave_spike") },
            { "Jester.Navigation.GoToResume", ("nav", "goto_resume_thinking", "") },
            { "Jester.Navigation.Holding.CurrentTurnPoint", ("nav", "hold_curr_wpt", "") },
            { "Jester.Navigation.Divert.LatLong", ("nav", "nav_enter_tgt_1_lat_long_text", "") },
            { "Jester.Navigation.TACAN.SelectMode.Off", ("nav", "nav_tacan_mode", "off") },
            { "Jester.Navigation.TACAN.SelectMode.R", ("nav", "nav_tacan_mode", "r") },
            { "Jester.Navigation.TACAN.SelectMode.TR", ("nav", "nav_tacan_mode", "tr") },
            { "Jester.Navigation.TACAN.SelectMode.AAR", ("nav", "nav_tacan_mode", "aar") },
            { "Jester.Navigation.TACAN.SelectMode.AATR", ("nav", "nav_tacan_mode", "aatr") },
            { "Jester.Systems.ChaffMode.Off", ("systems", "systems_chaff", "off") },
            { "Jester.Systems.ChaffMode.Single", ("systems", "systems_chaff", "single") },
            { "Jester.Systems.ChaffMode.Multiple", ("systems", "systems_chaff", "multiple") },
            { "Jester.Systems.ChaffMode.Program", ("systems", "systems_chaff", "program") },
            { "Jester.Systems.FlareMode.Off", ("systems", "systems_flare", "off") },
            { "Jester.Systems.FlareMode.Single", ("systems", "systems_flare", "single") },
            { "Jester.Systems.FlareMode.Program", ("systems", "systems_flare", "program") },
            { "Jester.Systems.Jammer.Standby", ("systems", "systems_jammer", "standby") },
            { "Jester.Systems.Jammer.Transmit", ("systems", "systems_jammer", "xmit") },
            { "Jester.Systems.AVTR.Record", ("systems", "systems_avtr_recorder", "record") },
            { "Jester.Systems.AVTR.Standby", ("systems", "systems_avtr_recorder", "standby") },
            { "Jester.Systems.AVTR.Off", ("systems", "systems_avtr_recorder", "off") },
            { "Jester.Crew.Presence.Auto", ("crew", "crew_presence", "auto") },
            { "Jester.Crew.Presence.Force", ("crew", "crew_presence", "enabled") },
            { "Jester.Crew.Presence.Disable", ("crew", "crew_presence", "disabled") },
            { "Jester.Crew.Talking.Talk", ("crew", "crew_talking", "talk") },
            { "Jester.Crew.Talking.Silence", ("crew", "crew_talking", "silence") },
            { "Jester.Crew.Ejection.WSO", ("crew", "crew_ejection", "wso") },
            { "Jester.Crew.Ejection.Both", ("crew", "crew_ejection", "both") },
            { "Jester.Crew.Countermeasures.Manual", ("crew", "crew_countermeasures", "manual") },
            { "Jester.Crew.Countermeasures.Jester", ("crew", "crew_countermeasures", "jester") },
        };
    }
}