using System;
using System.Collections.Generic;

namespace VAICOM.WSO
{
    public static class WSOAliases
    {
        // Aliases for WSO "Boots commands WIP - to be mapped to Jester wheel backend commands
        public static readonly Dictionary<string, string> CommandAliases = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Boots Report Speed",         "Jester.ReportSpeed"                },
            { "Boots Toggle Radar",         "Jester.ToggleRadar"                },
            { "Boots Set Chaff Mode",       "Jester.SetChaffMode"               },
            { "Boots Designate",            "Jester.Lantirn.Designate"          },
            { "Boots Undesignate",          "Jester.Lantirn.Undesignate"        },
            { "Boots Go Silent",            "Jester.Radar.GoSilent"             },
            { "Boots Go Active",            "Jester.Radar.GoActive"             },
            { "Boots Set Manual Frequency", "Jester.Radio.SetManualFrequency"   },
            { "Boots Select Comm Channel",  "Jester.Radio.SelectCommChannel"    },
            { "Boots Select Aux Channel",   "Jester.Radio.SelectAuxChannel"     },
            { "Boots Tune ATC",             "Jester.Radio.TuneATC"              },
            { "Boots Tune Assets",          "Jester.Radio.TuneAssets"           },
            { "Boots Select Mode",          "Jester.Radio.SelectMode"           },
            { "Boots Radar Active",         "Jester.Radar.Operation.Active"     },
            { "Boots Radar Standby",        "Jester.Radar.Operation.Standby"    },
            { "Boots Auto Focus On",        "Jester.Radar.AutoFocus.On"         },
            { "Boots Auto Focus Off",       "Jester.Radar.AutoFocus.Off"        },
            { "Boots IFF Both",             "Jester.Radar.IFF.Both"             },
            { "Boots IFF APX76",            "Jester.Radar.IFF.APX76"            },
            { "Boots Enter Boresight",      "Jester.Radar.Boresight.EnterBST"   },
            { "Boots Boresight Wide",       "Jester.Radar.Boresight.Wide"       },
            { "Boots Boresight Nose",       "Jester.Radar.Boresight.Nose"       },
            { "Boots Boresight Forward",    "Jester.Radar.Boresight.Forward"    },
            { "Boots Boresight Aft",        "Jester.Radar.Boresight.Aft"        },
            { "Boots Boresight Tail",       "Jester.Radar.Boresight.Tail"       },
            { "Boots Scan Center",          "Jester.Radar.ScanElevation.Center" },
            { "Boots Scan Low",             "Jester.Radar.ScanElevation.Low"    },
            { "Boots Scan Mid Low",         "Jester.Radar.ScanElevation.MidLow" },
            { "Boots Scan Far Low",         "Jester.Radar.ScanElevation.FarLow" },
            { "Boots Scan Close High",      "Jester.Radar.ScanElevation.CloseHigh" },
            { "Boots Scan Mid High",        "Jester.Radar.ScanElevation.MidHigh" },
            { "Boots Scan Far High",        "Jester.Radar.ScanElevation.FarHigh" },
            { "Boots Scan 25 Wide",         "Jester.Radar.ScanType.25Wide"      },
            { "Boots Scan 25 Narrow",       "Jester.Radar.ScanType.25Narrow"    },
            { "Boots Scan 50 Wide",         "Jester.Radar.ScanType.50Wide"      },
            { "Boots Scan 50 Narrow",       "Jester.Radar.ScanType.50Narrow"    },
            { "Boots Focus Target",         "Jester.Radar.FocusTarget"          },
            { "Boots Lock Target",          "Jester.Radar.LockTarget"           },
            { "Boots TV Weapons",           "Jester.A2G.TVWeapons"              },
            { "Boots TV Pave Spike",        "Jester.A2G.TVPaveSpike"            },
            { "Boots Go To Resume",         "Jester.Navigation.GoToResume"      },
            { "Boots Hold Current Turn Point", "Jester.Navigation.Holding.CurrentTurnPoint" },
            { "Boots Divert Lat Long",      "Jester.Navigation.Divert.LatLong"  },
            { "Boots TACAN Mode Off",       "Jester.Navigation.TACAN.SelectMode.Off" },
            { "Boots TACAN Mode R",         "Jester.Navigation.TACAN.SelectMode.R" },
            { "Boots TACAN Mode TR",        "Jester.Navigation.TACAN.SelectMode.TR" },
            { "Boots TACAN Mode AAR",       "Jester.Navigation.TACAN.SelectMode.AAR" },
            { "Boots TACAN Mode AATR",      "Jester.Navigation.TACAN.SelectMode.AATR" },
            { "Boots Chaff Mode Off",       "Jester.Systems.ChaffMode.Off"      },
            { "Boots Chaff Mode Single",    "Jester.Systems.ChaffMode.Single"   },
            { "Boots Chaff Mode Multiple",  "Jester.Systems.ChaffMode.Multiple" },
            { "Boots Chaff Mode Program",   "Jester.Systems.ChaffMode.Program"  },
            { "Boots Flare Mode Off",       "Jester.Systems.FlareMode.Off"      },
            { "Boots Flare Mode Single",    "Jester.Systems.FlareMode.Single"   },
            { "Boots Flare Mode Program",   "Jester.Systems.FlareMode.Program"  },
            { "Boots Jammer Standby",       "Jester.Systems.Jammer.Standby"     },
            { "Boots Jammer Transmit",      "Jester.Systems.Jammer.Transmit"    },
            { "Boots AVTR Record",          "Jester.Systems.AVTR.Record"        },
            { "Boots AVTR Standby",         "Jester.Systems.AVTR.Standby"       },
            { "Boots AVTR Off",             "Jester.Systems.AVTR.Off"           },
            { "Boots Crew Auto",            "Jester.Crew.Presence.Auto"         },
            { "Boots Crew Force",           "Jester.Crew.Presence.Force"        },
            { "Boots Crew Disable",         "Jester.Crew.Presence.Disable"      },
            { "Boots Talk",                 "Jester.Crew.Talking.Talk"          },
            { "Boots Silence",              "Jester.Crew.Talking.Silence"       },
            { "Boots Eject WSO",            "Jester.Crew.Ejection.WSO"          },
            { "Boots Eject Both",           "Jester.Crew.Ejection.Both"         },
            { "Boots Countermeasures Manual", "Jester.Crew.Countermeasures.Manual" },
            { "Boots Countermeasures Jester", "Jester.Crew.Countermeasures.Jester" },
        };
    }
}